### ISSUE TITLE
could u give FPS or FLOPs about Polyp-PVT,  i test this backbone, its so slow

### ISSUE THREAD

**Issue by csliuchang** [DengPingFan/Polyp-PVT#1]
if __name__ == "__main__":
    a = torch.randn(1, 3, 512, 512).cuda()
    backbone = pvt_v2_b0().cuda()
    start = time.time()
    out = backbone(a)
    end = time.time()-start
    print('each image use %5f seconds, and image size is 512' % end, )
    print([i.shape for i in out])
each image use 0.374312 seconds, and image size is 512
[torch.Size([1, 32, 128, 128]), torch.Size([1, 64, 64, 64]), torch.Size([1, 160, 32, 32]), torch.Size([1, 256, 16, 16])]

**Comment by dongbo811** [comment]
In our test, according to the environment [Tesla P100] input size [1,3,352,352] in our paper, the results obtained are as follows. FLOPs are about 10G, and the parameters are 25M. FPS has been tested many times due to server fluctuations, as shown in the figure below:
![image](https://user-images.githubusercontent.com/81909212/129681317-05e12964-b886-4e0a-953a-0e8a0664430c.png)
![image](https://user-images.githubusercontent.com/81909212/129681418-dfe78a56-0172-490b-80f8-b8434c708d3e.png)
![image](https://user-images.githubusercontent.com/81909212/129680817-7346197b-cc26-4aec-859a-09fc5f1ed8e9.png)
![image](https://user-images.githubusercontent.com/81909212/129681028-9d1116e7-ebf2-4313-b0aa-b85e244dcaf7.png)
